export const API_BASE_URL = "http://localhost:8080/api";

export const ORDER_STATUS = {
  PENDING: "PENDING",
  PROCESSING: "PROCESSING",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
  REFUNDED: "REFUNDED",
};

export const ROLES = {
  ADMIN: "ADMIN",
  USER: "USER",
  CUSTOMER: "CUSTOMER",
};
